langchain-ai/langchain-benchmarks

Makefile
csv-qa/custom_agent.py
csv-qa/pandas_agent_gpt_35.py
csv-qa/pandas_agent_gpt_4.py
csv-qa/pandas_agent_instruct.py
csv-qa/pandas_ai.py
csv-qa/streamlit_app.py
csv-qa/upload_data.py
extraction/streamlit_app.py
langchain-docs-benchmarking/app/server.py
langchain-docs-benchmarking/packages/anthropic-iterative-search/anthropic_iterative_search/retriever.py
langchain-docs-benchmarking/packages/chat-langchain/chat_langchain/chain.py
langchain-docs-benchmarking/packages/langchain-docs-retriever/langchain_docs_retriever/download_db.py
langchain-docs-benchmarking/packages/langchain-docs-retriever/langchain_docs_retriever/retriever.py
langchain-docs-benchmarking/packages/oai-assistant/oai_assistant/chain.py
langchain-docs-benchmarking/run_evals.py
langchain-docs-benchmarking/run_experiments.py
meta-evals/correctness/test_correctness_evaluator.py

Reformat all code base with ruff

Reformat entire codebase with ruff

---

Makefile

Add helper to Makefile

---

docs/source/index.md
docs/source/notebooks/datasets.ipynb

Add datasets notebook

---

langchain_benchmarks/extraction/email_task.py
langchain_benchmarks/registration.py
langchain_benchmarks/schema.py
langchain_benchmarks/tool_usage/environments/multiverse_math.py
langchain_benchmarks/tool_usage/environments/relational_data.py
langchain_benchmarks/tool_usage/environments/type_writer.py
langchain_benchmarks/tool_usage/environments/type_writer_26_funcs.py
tests/unit_tests/extraction/test_email_extraction.py

Add extraction task

---

langchain_benchmarks/schema.py

Remove ID that doens't exist

---

.github/workflows/doc_publish.yaml

Fix typo in workflow to publish docs

---

poetry.lock
pyproject.toml

Bump dependencies for doc building

---

langchain_benchmarks/tool_usage/tasks/multiverse_math.py
langchain_benchmarks/tool_usage/tasks/type_writer.py
langchain_benchmarks/tool_usage/tasks/type_writer_26_funcs.py
tests/unit_tests/tool_usage/test_multiverse_math.py

Add datasets for tool usage tasks

---

docs/source/toc.segment

Another toc update

---

README.md
docs/source/toc.segment

Update repo structure in readme

---

docs/source/notebooks/retrieval/comparing_techniques.ipynb
docs/source/notebooks/retrieval/langchain_docs_qa.ipynb
docs/source/notebooks/retrieval/semi_structured.ipynb

Device 0 default

---

docs/source/notebooks/tool_usage/multiverse_math.ipynb
docs/source/notebooks/tool_usage/relational_data.ipynb
docs/source/notebooks/tool_usage/typewriter_1.ipynb
docs/source/notebooks/tool_usage/typewriter_26.ipynb
langchain_benchmarks/tool_usage/evaluators.py
tests/unit_tests/tool_usage/test_evaluator.py

This updates the standard agent evaluator to use order_matters

Update standard agent evalutator

---

pyproject.toml

Version 0.0.4

---

langchain_benchmarks/tool_usage/evaluators.py
tests/unit_tests/tool_usage/test_evaluator.py

Make it easier to test an agent which isn't built from an agent executor

Make it easier to test non standard agents

---

docs/source/notebooks/models.ipynb
langchain_benchmarks/model_registration.py
langchain_benchmarks/schema.py

* Add more models
* Fix path to language models
* Notebook instantiates some of the models to test that it works

Update model registry

---

docs/source/notebooks/models.ipynb
langchain_benchmarks/model_registration.py

Add gpt-4 models

---

archived/langchain-docs-benchmarking/app/server.py
langchain_benchmarks/schema.py
poetry.lock
pyproject.toml

Minor change to bump ruff and fix up config

Bump ruff fix up first party identity for import sorting

---

langchain_benchmarks/schema.py

Code is already using `in` checks but they will fail since __contains__ isn't defined correctly

Add __contains__ to model registry

---

poetry.lock
pyproject.toml

Update min langsmith client

---

pyproject.toml

Bump requirement on minimal langsmith client

Version 0.0.10

---

langchain_benchmarks/tool_usage/agents/openai_functions.py

Needs to be the tool parser not the functions parser

Parser Fix

---

docs/source/notebooks/tool_usage/benchmark_all_tasks.ipynb
langchain_benchmarks/tool_usage/agents/anthropic_tool_user.py
langchain_benchmarks/tool_usage/agents/openai_functions.py

* Update open ai agent factory to be consistent with other factories.
* Update benchmark all to add anthropic sdk.

Update openai function factory, update benchmark all

---

langchain_benchmarks/tool_usage/tasks/multiverse_math.py

Update example in multiverse math

---

langchain_benchmarks/tool_usage/evaluators.py
langchain_benchmarks/tool_usage/prompts.py
langchain_benchmarks/tool_usage/tasks/multiverse_math.py

Try another evaluator that ignores the question

Update Math Evaluator

---

langchain_benchmarks/registration.py
langchain_benchmarks/tool_usage/tasks/multiverse_math.py

* This PR adds a multiverse math consisting of 20 questions.
* Question about rounding has been removed to simplify evaluation.

Change multiverse math to multiverse math (tiny) and add another multiverse math set

---

docs/source/notebooks/tool_usage/intro.ipynb
langchain_benchmarks/tool_usage/agents/__init__.py
langchain_benchmarks/tool_usage/agents/runnable_agent.py

Not sure if it's "easier" but it involves less thinking about benchmarking abstractions

Add runnable agent factory

---

.github/workflows/ci.yml
.github/workflows/doc_publish.yaml
Makefile

updated `Makefile`

---

langchain_benchmarks/model_registration.py
langchain_benchmarks/schema.py

* Update packages to be used with different providers
* Register Anthropic models

update model providers

---

docs/source/notebooks/tool_usage/benchmark_all_tasks.ipynb

Fix list of env variables in benchmark all notebook

---

docs/source/notebooks/tool_usage/intro.ipynb
langchain_benchmarks/tool_usage/agents/adapters.py

Remove confusing adapter for agents. Agent template should just take {question}
as the input.
Update intro and simplify it!

Update intro, remove adapter

---

docs/source/notebooks/tool_usage/benchmark_all_tasks.ipynb

Update benchmarks all notebook to use {question} instead of {input}
