langchain-ai/langchain-benchmarks

langchain_benchmarks/__init__.py, langchain_benchmarks/utils/_langsmith.py, poetry.lock, pyproject.toml, tests/unit_tests/test_public_api.py, tests/unit_tests/test_utils.py
Add langsmith util to clone dataset
=> Add langsmith util to clone dataset

langchain_benchmarks/__init__.py, langchain_benchmarks/utils/_langsmith.py, poetry.lock, pyproject.toml, tests/unit_tests/test_public_api.py, tests/unit_tests/test_utils.py
=> Add clone/download dataset, handle web vs. api paths

langchain_benchmarks/extraction/email_task.py, langchain_benchmarks/registration.py, langchain_benchmarks/schema.py, langchain_benchmarks/tool_usage/multiverse_math.py, langchain_benchmarks/tool_usage/relational_data.py, langchain_benchmarks/tool_usage/type_writer.py, langchain_benchmarks/tool_usage/type_writer_26_funcs.py, tests/unit_tests/tool_usage/test_tool_usage.py
Make it easier to make changes without merge conflicts
=> Refactor to remove ID from task, move task definitions out of registry.py

.github/workflows/ci.yml
=> Expand CI to also build sphinx docs

.github/workflows/doc_publish.yaml
Add workflow for publishing docs
=> Create doc publish workflow

poetry.lock, pyproject.toml
* Relax requirement for deps
* Bump langchain
* Bump langsmith
=> Update langchain, relax requirements for deps

langchain_benchmarks/rag/tasks/langchain_docs/indexing/retriever_registry.py, langchain_benchmarks/rag/tasks/langchain_docs/task.py, langchain_benchmarks/rag/tasks/semi_structured_earnings/indexing/retriever_registry.py, langchain_benchmarks/schema.py
Default list is long now. This would let you do something like
```
registry.filter(Type="RetrievalTask")
```
=> Add filter option

langchain_benchmarks/utils/_langsmith.py
Supposedly the cloud armor rule will be removed as well but keeping the placeholder for now
=> Switch to api

.github/workflows/ci.yml, langchain_benchmarks/utils/_langsmith.py, scripts/check_datasets.py
=> Check public datasets exist

docs/source/notebooks/extraction/email.ipynb, docs/source/notebooks/tool_usage/multiverse_math.ipynb, docs/source/notebooks/tool_usage/relational_data.ipynb, docs/source/notebooks/tool_usage/typewriter_1.ipynb, docs/source/notebooks/tool_usage/typewriter_26.ipynb, docs/source/toc.segment
=> Update notebooks toc

docs/source/notebooks/tool_usage/multiverse_math.ipynb, docs/source/notebooks/tool_usage/relational_data.ipynb, docs/source/notebooks/tool_usage/typewriter_1.ipynb, docs/source/notebooks/tool_usage/typewriter_26.ipynb
=> Minor documentation fixes

docs/source/notebooks/models.ipynb, docs/source/toc.segment, langchain_benchmarks/__init__.py, langchain_benchmarks/model_registration.py, langchain_benchmarks/schema.py, tests/unit_tests/test_model_registry.py, tests/unit_tests/test_public_api.py
Add a model registry to make it easier to iterate through models for bench-marking purposes
=> Add Model Registry

langchain_benchmarks/schema.py, langchain_benchmarks/tool_usage/evaluators.py, langchain_benchmarks/tool_usage/tasks/multiverse_math.py, langchain_benchmarks/tool_usage/tasks/relational_data.py, langchain_benchmarks/tool_usage/tasks/type_writer.py, langchain_benchmarks/tool_usage/tasks/type_writer_26_funcs.py
This will make it easier to treat all tasks uniformly.
=> Tool Tasks: Add eval params to task definition

docs/source/notebooks/tool_usage/benchmark_all_tasks.ipynb, langchain_benchmarks/schema.py
* This PR adds a notebook that benchmarks all tool usage tasks.
To make it easier to work with task registry:
* Add `type` property to tasks.
* Add __iter__ and __len__ and support for slices in __item__ for task
registry.
=> Benchmark all tool usage notebook

langchain_benchmarks/__init__.py, langchain_benchmarks/rate_limiting.py, langchain_benchmarks/tool_usage/agents.py, poetry.lock, pyproject.toml, tests/unit_tests/test_public_api.py, tests/unit_tests/test_rate_limiting.py
This PR adds a simple rate limiter based on a token bucket.
I would love to extend RunnableBinding with this, we just need to make
sure there's no funny async vs. threading business.
This should be sufficient for benchmarking for now.
=> Add rate limiter

langchain_benchmarks/__init__.py, langchain_benchmarks/tool_usage/agents.py, tests/unit_tests/test_public_api.py
Because it's not a runnable binding it breaks things like .bind etc, let's use
it internally but not expose to users
=> remove with_rate_limit from public api

langchain_benchmarks/model_registration.py
=> Update fireworks models

langchain_benchmarks/__init__.py, langchain_benchmarks/tool_usage/agents/adapters.py, langchain_benchmarks/tool_usage/agents/experimental/agent.py, langchain_benchmarks/tool_usage/agents/experimental/parser.py, langchain_benchmarks/tool_usage/agents/experimental/tool_utils.py, langchain_benchmarks/tool_usage/agents/openai_functions.py, tests/unit_tests/agents/encoding_and_decoding/test_decoding.py, tests/unit_tests/test_public_api.py
=> Add version

langchain_benchmarks/tool_usage/agents/__init__.py, langchain_benchmarks/tool_usage/agents/anthropic_tool_user.py, langchain_benchmarks/tool_usage/agents/openai_functions.py
For benchmarking, this is comparing against anthropic implementation.
=> Add anthropic agent based on tool user repo

docs/source/notebooks/tool_usage/benchmark_all_tasks.ipynb, langchain_benchmarks/tool_usage/agents/__init__.py, langchain_benchmarks/tool_usage/agents/anthropic_tool_user.py, langchain_benchmarks/tool_usage/agents/openai_assistant.py, langchain_benchmarks/tool_usage/agents/openai_functions.py, langchain_benchmarks/utils/__init__.py
Similar to our functions agent
=> OAI Assistant

docs/source/notebooks/retrieval/comparing_techniques.ipynb
Fixing a missing word in https://langchain-ai.github.io/langchain-benchmarks/notebooks/retrieval/comparing_techniques.html
The sentence after the heading is incomplete since I have added the word `documents` which would complete the sentence.
Before changing:
=> Missing Word in comparing_techniques.ipynb

langchain_benchmarks/registration.py, langchain_benchmarks/tool_usage/tasks/multiverse_math.py
Keep it for backwards compatibility but do not expose in task registry. This dataset is probably more confusing to folks than helpful especially since it it completely overlaps with the existing multiverse math dataset. We should add another dataset that's later.
=> remove tiny multiverse dataset from registry
